      const options = [
        "REMEMBER TO TURN OFF YOUR INTERNET",
        "Math Helpers v2 Is Trash",
        "The Yes",
        "Who Told The Admins",
        "Kahoot Vs Blooket",
        "Mustard Gas (IFYKYK)",
        "Me And My Monkey",
        "3/3/2023",
        "Mr Moreno Fresh Cut",
        "We Do a Bit of Trolling",
        "GoGuardian Is Trash",
        "This Text Was Blocked By Your Administrator",
        "Coughing Baby Vs Hydrogen Bomb",
        "School Admins Be Ballin Rn",
        "Bro Trust, They Wont Block It",
        "Admins Found The Games Website",
        "/gamemode creative",
        "esc + reload + power",
        "Never Gonna Give You Up",
        "I Never Needed Bitches",
        "Go To The Office",
        "BumBum",
        ":)",
        "You Think Your Safe?",
        "Four Big Guys",
        "They Locked My Chromebook",
        "Dont Forget",
        "Shrek Is Best Movie",
        "Cineb.net (Thank Me Later)",
        "I Did It My Way",
        "Listening To Minecraft Music, Im Crying",
        "Jingle Bell, Jingle Bell, Jingle Bell Rock",
        "All I Want For Christmas Is You",
        "Remember When FNF Was Popular",
        "Have A Good Day",
        "Dink Some Water!",
        "I Hope Your Day Is Going Good",
        "Do It",
        "I Found A Golf Club Under A Fence",
        "I See You.",
        "If Your Happy And You Know It Clap Your Hands",
        "Jesus",
        "Omg Is That Ronnald McDonnald",
        "The Pac Is Back",
        "5 Little Monkeys Jumping On The Bed",
        "One Fell Off And Bonked His Head",
        "So Mommy Called The Doctor And The Doctor Said",
        "No More Monkeys Jumping On The Bed!",
        "Ring Around The Rosies",
        "Connection Terminated",
        "Dont Keep The Devil Waiting",
        "Yipee",
        "Door To Bell",
        "This Is A Hood Classic",
        "Uh Oh",
      ];

      function changeText() {
        const randomIndex = Math.floor(Math.random() * options.length);
        const randomText = options[randomIndex];
        document.getElementById("random-h1").textContent = randomText;
      }
